### ISSUE TITLE
member.interests should return [] not null.

### ISSUE THREAD

**Issue by csell5** [ThatConference/that-api-members#73]
Currently members.member.interests returns null if there are no interests. I'm guessing that's because interests might not have ever been set for that user. It would be nice if that defaulted to an empty array rather than null.

**Comment by brettski** [comment]
Interests is an array field in Firestore. Most users don't have this field so it will return as null/undefined.

I am not sure on the best approach here. Some initial thoughts:

1. update all records to include an `interests` field
1. update cloudFirestore queries to include an `interests` field if not present. 
  - this seems a bit error prone and would need to be remembered in future updates
1. update resolver to handle a missing `interests` field.
  - this feels wrong like the last one

**Comment by brettski** [comment]
The more I thought about this, the data should be fixed. A two+ step process is in place. 

1. Update members api to ensure the `interests` field is always written. If there is no value set, `[]` will be written. 
2. Run a query to update all current records where `interests` doesn't exist or is set to `null`. 
3. update that-website to correctly write value to database. (less important due to 1 being in place)

**Comment by brettski** [comment]
This has been corrected. As per my last comment:
1. pr merged which ensure that the `interests` field exists and is an array value. 
1. member records updated so all have an `interests` field and that field has an array value
1. issue has been created in that-website for it writing null to interest field thatconference/that-website#595
